/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    CalStepperGuide: typeof import('./components/calibration/CalStepperGuide.vue')['default']
    CalWizard: typeof import('./components/calibration/CalWizard.vue')['default']
    ChannelGrid: typeof import('./components/channel/ChannelGrid.vue')['default']
    ElrsFieldTree: typeof import('./components/elrs/ElrsFieldTree.vue')['default']
    FirmwareUpgradeDialog: typeof import('./components/FirmwareUpgradeDialog.vue')['default']
    OutputCurveEditor: typeof import('./components/config/OutputCurveEditor.vue')['default']
    OutputCurvePanel: typeof import('./components/calibration/OutputCurvePanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderLabel: typeof import('./components/SliderLabel.vue')['default']
  }
}
